#server:
#  port: 8888

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
    #datasource:
      #默认加载的是target目录下的文件
      url: jdbc:mysql://localhost:3306/dlpr?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: SHENGri19870118!!
      max-active: 10 #最大连接数
      min-idle: 5 #最小连接数
      max-wait: 10000 #获取连接的最大等待时间
      time-between-eviction-runs-millis: 60000 #空闲连接的检查时间间隔
      min-evictable-idle-time-millis: 300000 #空闲连接最小空闲时间

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    lazy-loading-enabled: false
    call-setters-on-nulls: true
